travis:
  secure:
    BINSTAR_TOKEN: GcRpc6HXFm/5idsqEQMzi/InAT0/tks6RC9Lj0e3ymwJztZJYYcUjmVWknSreyu71jC6nu66lQeK3OjvD1MRR2yZ5wbNWkMiILCu33hSvx3NFONRaf7JC4MXv+ENrk5GZDiLo3ORTHmN+kppxvldtcyCB3zixAJxzYTDkDF0EIoHfByR8nrWYo18zEvb4vODu8mERjvuXEzkFrFNd+Zl48WhWD9hdDN18GocAtV4gpSCoNc9tHyA7vaZsk24w3ra19tXK1tgU1zPaI6BIs0qtLg8U+tAlqwEJ1Yephkc41kgEh0m9nh1v0jR0T32SHuxH7imzoYHZ+yhYUjhpcB5pysEBh6g1RYDEs8Jg9HGfLORMaxZyuYdLG4/Py9rpfHo7rbViN5HwZpg0X7iNIhMOeVU80mQbNvWpgfCuuG0++HG5usRfhPKNm2k4pyBUvdutcKp418V7g/2ddp0RVTncKCMSOWDIVnf5fulSbzuSy0x8TCdJXo6WTQ236FCqk6NtKUnn2pRgfDfL1WWobGgdqMdSG1ys9eURnMJxw81cAyglBFF9+zOtluP0E8EJGvd7J8Jf1pBeKpOjr3rMPK7+GhXzivpvcmDDeV/g1nibBmZX0o2Ru6lwVo4MgOWfPzkeLo0rwhY0v/n8or0MjmSYVRZdZNtMHli/4PawZRTDhI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
